### ISSUE TITLE
NexT v8 Roadmap

### ISSUE THREAD

**Issue by stevenjoezhang** [theme-next/hexo-theme-next#1029]
## Requested features:

- [ ] Search filters on archives / cats / tags ([#424](https://github.com/iissnan/hexo-theme-next/issues/424))
- [ ] Language switcher by flags? ([#1680](https://github.com/iissnan/hexo-theme-next/issues/1680), #1070)
- [ ] local search obscure lookup ([#1695](https://github.com/iissnan/hexo-theme-next/issues/1695))
- [ ] Sidebar on mobile for all schemes (not only for Muse | Mist, #281).
- [ ] Refactor motion (animate.css).
- [ ] Menu slidedown animation on mobile (without Velocity).
- [ ] Suggest to support "like coin" under each post

## Known issues:

- [ ] `border-radius` not working correctly with `.highlight` element (style: mac).
- [ ] Affix bug (https://github.com/iissnan/hexo-theme-next/commit/12808375bed33801ef597640b2280711529bd1f2, https://github.com/theme-next/hexo-theme-next/issues/846, https://github.com/theme-next/hexo-theme-next/pull/1039)
- [ ] PJAX issues: read_more & comments (https://github.com/MoOx/pjax/issues/22, https://github.com/darylteo/pjax/commit/4893a2a6574b3490396f83a1863499e8a9ba171e)

## Miscellaneous:

- [ ] Refactor the style of Pisces / Gemini using `flex` layout. (Instead of `float: right / left`)
- [ ] Migrate to Algolia InstantSearch 3
- [ ] Migrate to Mathjax 3
- [ ] Lazy loading via attribute for images & iframes

## To be discussed:

- [ ] Use `em` as unit of sidebar-toggle and b2t margin (https://github.com/theme-next/hexo-theme-next/pull/808#issuecomment-479973233)
- [ ] Bash symbols will be copied while clicking the copy-button. (https://github.com/theme-next/hexo-theme-next/pull/977#issuecomment-512134210)

***
Please feel free to leave your thought in comments (or edit this post directly if u have permissions).

**Comment by hsiangfeng** [comment]
其實我一直在想是不是可以加入一個固定幾個 Google Adsense 區塊，因為許多人都會去修改 NexT 加入 Adsense(包含我自己)。

目前思考的位子在於文章內文頂頭、文章尾段，側邊功能列，會這樣思考的原因在於自動插入 Google 廣告的作法並不是非常好看，導致畫面較混亂。

**Comment by yuebaiqinghui** [comment]
代码块能否整合codemirror以便更好的阅读

**Comment by stevenjoezhang** [comment]
@yuebaiqinghui This is a feature that Hexo is responsible for, not theme NexT. You can join the discussion here: https://github.com/hexojs/hexo/issues/4010

**Comment by stevenjoezhang** [comment]
If `notes` are used in `tabs`, then `hexo.render.renderSync` will be executed twice on the contents of notes. When using `hexo-renderer-pandoc`, this will escape the html content.
