### ISSUE TITLE
Migrate to Nunjucks

### ISSUE THREAD

**Issue by 1v9** [theme-next/hexo-theme-next#1214]
#### Any developer could log issues here, see [njk](https://github.com/theme-next/hexo-theme-next/tree/njk), should use Hexo v4/master version.
---
Hexo:
- [ ] `TypeError: Cannot read property 'replace' of null at Hexo.externalLinkFilter`
- [ ] `TypeError: Cannot read property 'match' of null at Hexo.hexoMetaGeneratorInject`
---
NexT plugin:
- [x] `Error: filter not found: json_encode`(use `dump` in [hexo-next-title](https://github.com/theme-next/hexo-next-title))
---
On the road:
> when disable external_link, meta_generator
- [ ] all pages show `null` except archive page, no errors again.
- [ ] layout\archive.swig [Line 29, Column 11] - `Unhandled rejection Template render error: unknown block tag: endif`
- [ ] layout\archive.swig [Line 40, Column 5] - `Unhandled rejection Template render error:  unknown block tag: endfor`
https://github.com/theme-next/hexo-theme-next/pull/1068#issuecomment-518756742

---
Pending:
- [ ] layout\_partials\head\head.swig - `TypeError: Cannot read property 'charAt' of undefined`
- [ ] layout\_scripts\vendors.swig) - `TypeError: Cannot read property 'charAt' of undefined`
- [ ] layout\_partials\header\menu.swig [Line 8, Column 25] - `Unable to call `__`, which is undefined or falsey`
- [ ] layout\_macro\post.swig) [Line 223, Column 61] - `expected block end in include statement`
- [ ] layout\index.swig) [Line 18, Column 28] - `Unable to call `__`, which is undefined or falsey`
- [ ] layout\_partials\footer.swig) [Line 12, Column 33] - `Unable to call `Date["now"]`, which is undefined or falsey`
- [ ] layout\_third-party\search\index.swig - `template not found: localsearch.swig`

**Comment by stevenjoezhang** [comment]
References:
https://github.com/AlynxZhou/hexo-renderer-nunjucks/issues/1
https://github.com/mozilla/nunjucks/issues/307
https://github.com/mozilla/nunjucks/pull/1209
https://github.com/mozilla/nunjucks/issues/569

**Comment by stevenjoezhang** [comment]
PRs:
https://github.com/theme-next/hexo-theme-next/pull/1068
https://github.com/theme-next/hexo-theme-next/pull/1215

**Comment by stevenjoezhang** [comment]
Benchmark (Need more test cases)
https://github.com/stevenjoezhang/nunjucks-vs-swig

**Comment by stevenjoezhang** [comment]
https://medium.com/engineers-optimizely/js-templating-transitioning-from-swig-to-nunjucks-ac0e94d1794b

**Comment by AlynxZhou** [comment]
Ah, although I use neither Hexo nor NexT now, I can still help about things of nunjucks plugin, though I have not upload my plugin a lot time, I think it's still the newest alive nunjucks plugin.

By the way, it's name on <https://npmjs.com> is called `hexo-renderer-njucks` because `hexo-renderer-nunjucks` `hexo-renderer-njks` `hexo-renderer-njk` are all dead.

**Comment by AlynxZhou** [comment]
About `Unable to call Date["now"], which is undefined or falsey`:
Nunjucks does not work like ejs or swig, which treat expressions as JavaScript expressions, you need to register JavaScript function them and then you can use them, so try to passing them via Hexo, I am not familiar to how to do this with Hexo, but it should work.

**Comment by stevenjoezhang** [comment]
@AlynxZhou Thanks so much!

**Comment by stevenjoezhang** [comment]
Thanks, I'll check for that.
Moreover, your theme - hexo-theme-aria, is pretty nice. I have already referenced some code from it, otherwise I might waste a whole day figuring out why `page.posts` in for tag doesn't work with out `toArray()` 😂

**Comment by stevenjoezhang** [comment]
Jobs done
