### ISSUE TITLE
Please let `on mobile` support Pisces / Gemini scheme

### ISSUE THREAD

**Issue by liangchenhe55** [theme-next/hexo-theme-next#281]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/). **! It is still under construction !**
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
> This is just a suggestion, not a bug.

 Let 「on mobile」support Pisces scheme. I think it is fine that display as same as in Muse, or there may be a better solution. Just in my point of view, the sidebar is very important.
### Actual behavior 
Only for Muse | Mist

### Steps to reproduce the behavior 
1. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [x] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml

```

**Comment by sli1989** [comment]
Mentioned in [NexT 7.0 Roadmap](https://github.com/theme-next/hexo-theme-next/issues/67).

**Comment by stevenjoezhang** [comment]
Mentioned in NexT v8.x Roadmap (#809)
It seems that you have migrated to wordpress 😂

**Comment by stevenjoezhang** [comment]
Mentioned in NexT v8.x Roadmap (#809)
It seems that you have migrated to wordpress 😂

**Comment by lovelyMircho** [comment]
My app no problem

**Comment by stevenjoezhang** [comment]
Thank you for your patience, this feature is added in https://github.com/next-theme/hexo-theme-next/pull/710
