### ISSUE TITLE
Add disqusJS comment system

### ISSUE THREAD

**Issue by haig233** [theme-next/hexo-theme-next#586]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

#### Hexo version

```

```

#### Hexo Configuration

```yml

```

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [ ] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [X] All schemes
- [X] Muse
- [X] Mist
- [X] Pisces
- [X] Gemini

#### NexT Configuration:

```yml

```

### Other Information 
建议添加disqusJS评论

**Comment by stevenjoezhang** [comment]
Is it this one: https://github.com/SukkaW/DisqusJS ?

**Comment by haig233** [comment]
@stevenjoezhang yes

**Comment by stevenjoezhang** [comment]
Added to roadmap(https://github.com/theme-next/hexo-theme-next/issues/67)

**Comment by JiangTJ** [comment]
If not complete, maybe keep opening

**Comment by JiangTJ** [comment]
In most cases, close equals done.
In project, card would also move to done.

**Comment by ivan-nginx** [comment]
And project cards semi-automatic, yep.
