### ISSUE TITLE
Applications & Bots Testing

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#786]
- [x] AllContributors → Working, but fine tuning required.
- [x] ~~Auto Assign~~ → Add reviewers work, add assigners disabled.
- [ ] Background Check
- [x] ~~Delete merged branch~~ → Working without settings, from the box.
- [ ] ESLint Disable Watcher
- [x] ~~Invite Contributors~~ → Worked, @asdf2014 successfully invited by bot.
- [x] ~~Lock~~ → [Working too](https://github.com/theme-next/hexo-theme-next/issues/57#issuecomment-478419806), but maybe need to ~~add `Locked` label~~? Added, need to ensure in this.
      ~~**Don't touch #207 issue (will be tested on 3 Apr 2018)**.~~ Locked by [bot](https://github.com/theme-next/hexo-theme-next/issues/207#issuecomment-479302059).
      To see which issues will be locked: `is:issue is:closed is:unlocked updated:<2018-05-01`
- [x] ~~Mergeable~~ → Perfect app, worked (with 1 detected bug: during switching Projects, bot don't catch it).
- [x] Polls → It seems polls working only in new issues, they don't work in comments.
- [x] Release Drafter → Troubles with rewriting (Breaking Changes); need to add `v6` category.
- [x] ~~Request Info~~ → Exclude worked, see #790 & #791. ~~Label not added.~~ Mistake, worked.
- [x] ~~Sentiment Bo~~t → Keep calm 😉
- [x] Stale → Working fine, but maybe can be replaced by another bot.
- [x] ~~Support~~ → [Worked perfectly](https://github.com/theme-next/hexo-theme-next/issues/772#issuecomment-478833455).
- [x] ~~To-Do~~ → Already tested in own account, working, assigning. Interesting bot.
- [x] ~~Top Issues~~ → Scanning every 25 minutes, adding `Top Issue!` label on top 10 issues (with +1 emoji). 
- [x] ~~Unfurl Links~~ → Working in comments of Issue and PR.
- [x] ~~Untrivializer~~ → Working perfectly :smile: 
- [x] Weekly Digest → It seems working fine too: #772. But need to change `weekly-digest` label.
- [x] ~~Welcome~~ → Working in New Issue and New PR.

**Comment by 1v9** [comment]
https://github.com/MoOx/pjax

**Comment by 1v9** [comment]
Fuck Trump

**Comment by ivan-nginx** [comment]
ahahahahaha lol fcking bot give me the laught

**Comment by ivan-nginx** [comment]
Worked. :+1:
