### ISSUE TITLE
NexT v7.5 Roadmap

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/hexo-theme-next#809]
## Requested features:

- [ ] Search filters on archives / cats / tags ([#424](https://github.com/iissnan/hexo-theme-next/issues/424))
- [x] Fluidbox or mediumZoom? ([#394](https://github.com/iissnan/hexo-theme-next/issues/394), #627) (Added in #987)
- [x] PJAX support. ([#918](https://github.com/iissnan/hexo-theme-next/issues/918), added in #1024)
- [ ] Language switcher by flags? ([#1680](https://github.com/iissnan/hexo-theme-next/issues/1680), #1070)
- [ ] local search obscure lookup ([#1695](https://github.com/iissnan/hexo-theme-next/issues/1695))
- [x] Night Mode on NexT. ([#1871](https://github.com/iissnan/hexo-theme-next/issues/1871), https://github.com/1v9/hexo-next-nightmode)
- [x] `spoiler` tag. (#200) (Use https://github.com/fletchto99/hexo-sliding-spoiler + codeblock)
- [ ] Sidebar on mobile for all schemes (not only for Muse | Mist, #281).
- [x] Refactor page-type-quote. (https://github.com/theme-next/hexo-theme-next/pull/953#issuecomment-509559646)
- [x] Replace swig engine with nunjucks (currently Hexo uses nunjucks, #1068, #1161)
- [ ] ~~Variable templates on schemes with misc colors (not only black-white).~~
- [ ] ~~Changing color templates with JS directly and save to cache.~~
- [ ] Refactor motion (animate.css).
- [ ] Menu slidedown animation on mobile (without Velocity).

### Third-party plugins:

- [x] Google / Yandex maps tags. (Use https://github.com/the-simian/hexo-tag-googlemaps)
- [x] Transform latex expression to svg in build time? (Use https://github.com/stevenjoezhang/hexo-filter-mathjax)

## Known issues:

- [ ] `border-radius` not working correctly with `.highlight` element (style: mac).
- [ ] Affix bug (https://github.com/iissnan/hexo-theme-next/commit/12808375bed33801ef597640b2280711529bd1f2, https://github.com/theme-next/hexo-theme-next/issues/846, https://github.com/theme-next/hexo-theme-next/pull/1039)
- [ ] PJAX issues: read_more & comments (https://github.com/MoOx/pjax/issues/22, https://github.com/darylteo/pjax/commit/4893a2a6574b3490396f83a1863499e8a9ba171e)
- [x] `<script type="text/x-mathjax-config">` refreshed by PJAX.

## Miscellaneous:

- [x] Console reminder if new version released [autoupdate option] (#318) (Added in #1002)
- [x] Drop IE support (#557, #590, #843): Replace all Nested Strings by Template Literals. (#567, #587) (#1023)
- [x] Reimplement Bootstrap affix (https://github.com/theme-next/hexo-theme-next/pull/1039#issuecomment-516846195, Fixed in #1130)
- [x] Use `fetch` instead of `$.ajax`.
- [x] Rename `scripts/merge-configs.js`. (#1003)
- [x] AppVeyor & Build automatization scripts.
- [ ] ~~Separate schemes on modules / submodules.~~
- [ ] ~~Separate styles between schemes (exclude all possible styles rewrites).~~
- [ ] ~~Refactor all separated transactions on one global transaction.~~
- [x] Refactor Muse menu on mobile. (Fixed in #1014)
- [ ] ~~Move all possible docs with features from config to site with docs.~~

## To be discussed:

- [ ] Use `em` as unit of sidebar-toggle and b2t margin (https://github.com/theme-next/hexo-theme-next/pull/808#issuecomment-479973233)
- [ ] Bash symbols will be copied while clicking the copy-button. (https://github.com/theme-next/hexo-theme-next/pull/977#issuecomment-512134210)

***
Please feel free to leave your thought in comments (or edit this post directly if u have permissions).

**Comment by stevenjoezhang** [comment]
Replace `$.Velocity` with `window.Velocity` (or `Velocity`) after removing jQuery (#1116)

**Comment by stevenjoezhang** [comment]
Replace classname with id? https://jsperf.com/id-vs-class

**Comment by ivan-nginx** [comment]
Yes, that what i'm talking about. Think about it.

**Comment by hsiangfeng** [comment]
wow . Looking forward to Night Mode~🤩

**Comment by jiangtj** [comment]
> wow . Looking forward to Night Mode~🤩

Try this https://github.com/1v9/hexo-next-nightmode

**Comment by stevenjoezhang** [comment]
Refactor the style of Pisces / Gemini using `flex` layout. (Instead of `float: right / left`)

**Comment by Gabirel** [comment]
Any updates for `Language switcher by flags()?`https://github.com/iissnan/hexo-theme-next/issues/1680 and https://github.com/theme-next/hexo-theme-next/issues/1070

**Comment by hsuanyi-chou** [comment]
Suggest to support "like coin" under each post
it's already supported by medium and wordpress!

Also adsense.
so many users add adsense by themself (including me). each time upgrading theme version costs lots of time to adjust adsense!

thanks !

**Comment by stevenjoezhang** [comment]
Migrate from Algolia InstantSearch 2 to InstantSearch 3

https://github.com/algolia/instantsearch.js/blob/879aa20d3c1e2fe906bc526b05c57f6847c433be/docgen/src/guides/v3-migration.md

**Comment by stevenjoezhang** [comment]
escape or json filter

https://github.com/theme-next/hexo-theme-next/issues/494
https://github.com/theme-next/hexo-theme-next/pull/506/files
https://github.com/theme-next/hexo-theme-next/commit/ef79359af221054de2af1676e69234f0e2ee20cd

**Comment by stevenjoezhang** [comment]
> Increase site loading speed in Google Speed Insights.

https://developers.google.com/speed/pagespeed/insights/?url=theme-next.org
https://gtmetrix.com/reports/theme-next.org/shzxujHR
https://www.webpagetest.org/result/191012_75_cd652acc81f6006d1aac5f6a86513786/

**Comment by stevenjoezhang** [comment]
Lodash merge or Object.assign
https://github.com/theme-next/hexo-theme-next/pull/970
https://github.com/theme-next/hexo-theme-next/commit/74f27495b993f338633c985a11e243ea7499a1e4
https://github.com/hexojs/hexo/issues/3753

**Comment by stevenjoezhang** [comment]
优化local-search，例如模糊查找功能 https://github.com/iissnan/hexo-theme-next/issues/1695

**Comment by stevenjoezhang** [comment]
Drop cheerio: https://github.com/hexojs/hexo/pull/3850

**Comment by stevenjoezhang** [comment]
Lazy loading via attribute for images & iframes

https://caniuse.com/#feat=loading-lazy-attr
https://addyosmani.com/blog/lazy-loading/
https://github.com/ruanyf/markdown-it-image-lazy-loading

**Comment by stevenjoezhang** [comment]
[Exif.js](https://github.com/exif-js/exif-js)

```js
//<script src="https://cdn.jsdelivr.net/npm/exif-js"></script>

	function getExif(target) {
		EXIF.getData(target, function() {
			var FocalLength  = EXIF.getTag(this, 'FocalLength');
			var FNumber      = EXIF.getTag(this, 'FNumber');
			var ExposureTime = EXIF.getTag(this, 'ExposureTime');
			if (FocalLength && FNumber && ExposureTime) {
				if (ExposureTime <= 0.25) {
					ExposureTime = '1/' + parseInt(1 / ExposureTime);
				}
				$(target).after(`<p class="image-caption">${FocalLength}mm f/${FNumber} ${ExposureTime}s</p>`);
			}
		});
	}

	[...document.querySelectorAll('.post-body img')].forEach(element => {
		element.complete ? getExif(element) : element.addEventListener('load', () => {
			getExif(element);
		});
	});
```

**Comment by stevenjoezhang** [comment]
Superseded by https://github.com/theme-next/hexo-theme-next/issues/1029
