### ISSUE TITLE
Post-meta-divider is shown when created_at and updated_at disabled 

### ISSUE THREAD

**Issue by jiangtj** [theme-next/hexo-theme-next#867]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.org/docs/).
- [x] And yes, I already searched for current [issues](https://github.com/theme-next/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
![image](https://user-images.githubusercontent.com/15902347/57274850-16870780-70cf-11e9-9476-2b576dabe12b.png)
Post-meta-divider is shown when created_at and updated_at disabled.

### Steps to reproduce the behavior 
1. Disable post mate created_at and updated_at

* Link to demo site with this bug: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

- [ ] Latest Master branch
- [x] Latest Release version
- [ ] Old version

**NexT Scheme:**

- [x] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

#### NexT Configuration:

```yml
post_meta:
  created_at: false
  updated_at:
    enable: false
```

**Comment by JiangTJ** [comment]
Use border-right (`CSS :first-child` hide first border) replace divider may be a good way.
http://www.w3school.com.cn/cssref/selector_first-child.asp
